include ../Makefile.inc

OBJLIBS	= ../lib_go_root.a ../lib_go_base.a
OBJS =	go_root.o

all: $(OBJLIBS)

../lib_go_root.a:
	$(ECHO) lib_go_root

../lib_go_base.a:
	$(ECHO) lib_go_base

force_look:
	true
