/*
  Copyrights reserved
  Written by Paul Hwang
  File name: fabric_theme_protocol.h
*/

#pragma once

#define FABRIC_THEME_PROTOCOL_COMMAND_IS_MALLOC_ROOM 'R'
#define FABRIC_THEME_PROTOCOL_RESPOND_IS_MALLOC_ROOM 'r'
#define FABRIC_THEME_PROTOCOL_COMMAND_IS_GET_SESSION_DATA 'G'
#define FABRIC_THEME_PROTOCOL_RESPOND_IS_GET_SESSION_DATA 'g'
#define FABRIC_THEME_PROTOCOL_COMMAND_IS_PUT_SESSION_DATA 'P'
#define FABRIC_THEME_PROTOCOL_RESPOND_IS_PUT_SESSION_DATA 'p'
