/*
  Copyrights reserved
  Written by Paul Hwang
  File name: web_fabric_protocol.h
*/

#pragma once

#define WEB_FABRIC_PROTOCOL_COMMAND_IS_MALLOC_LINK 'L'
#define WEB_FABRIC_PROTOCOL_RESPOND_IS_MALLOC_LINK 'l'
#define WEB_FABRIC_PROTOCOL_COMMAND_IS_MALLOC_SESSION 'S'
#define WEB_FABRIC_PROTOCOL_RESPOND_IS_MALLOC_SESSION 's'
#define WEB_FABRIC_PROTOCOL_COMMAND_IS_TRANSFER_SESSION_DATA 'P'
#define WEB_FABRIC_PROTOCOL_RESPOND_IS_TRANSFER_SESSION_DATA 'p'

#define WEB_FABRIC_PROTOCOL_COMMAND_IS_GET_SESSION_DATA 'G'
#define WEB_FABRIC_PROTOCOL_RESPOND_IS_GET_SESSION_DATA 'g'
