/*
  Copyrights reserved
  Written by Paul Hwang
  File name: link_mgr_protocol.h
*/

#pragma once

#define LINK_MGR_PROTOCOL_COMMAND_IS_MALLOC_BASE 'M'
#define LINK_MGR_PROTOCOL_RESPOND_IS_MALLOC_BASE 'm'
#define LINK_MGR_PROTOCOL_COMMAND_IS_FREE_BASE 'F'
#define LINK_MGR_PROTOCOL_RESPOND_IS_FREE_BASE 'f'
#define LINK_MGR_PROTOCOL_COMMAND_IS_TRANSFER_DATA 'D'
#define LINK_MGR_PROTOCOL_RESPOND_IS_TRANSFER_DATA 'd'

#define LINK_MGR_PROTOCOL_GAME_NAME_IS_GO 'G'

#define LINK_MGR_DATA_BUFFER_SIZE 512

#define LINK_MGR_PROTOCOL_BASE_ID_SIZE 4
#define LINK_MGR_PROTOCOL_BASE_INDEX_SIZE 4
#define LINK_MGR_PROTOCOL_BASE_ID_INDEX_SIZE (LINK_MGR_PROTOCOL_BASE_ID_SIZE + LINK_MGR_PROTOCOL_BASE_INDEX_SIZE)
