/*
  Copyrights reserved
  Written by Paul Hwang
  File name: go_port_class.cpp
*/

#define GO_PROTOCOL_GAME_INFO 'G'
#define GO_PROTOCOL_TIME_INFO 'T'
#define GO_PROTOCOL_CHAT_INFO 'C'
#define GO_PROTOCOL_MOVE_COMMAND 'M'
#define GO_PROTOCOL_PASS_COMMAND 'P'
#define GO_PROTOCOL_BACKWARD_COMMAND 'b'
#define GO_PROTOCOL_DOUBLE_BACKWARD_COMMAND 'B'
#define GO_PROTOCOL_FORWARD_COMMAND 'f'
#define GO_PROTOCOL_DOUBLE_FORWARD_COMMAND 'F'
#define GO_PROTOCOL_RESIGN_COMMAND 'R'
#define GO_PROTOCOL_CONFIRM_COMMAND 'C'
#define GO_PROTOCOL_CONTINUE_COMMAND 'c'
