include ../Makefile.inc

OBJLIBS	= ../lib_utils.a
OBJS =	logit.o transport_class.o

all: $(OBJLIBS)

../lib_utils.a:
	$(ECHO) lib_utils

clean:
	$(ECHO) cleaning up in utils

force_look:
	true

