include ../../Makefile.inc

OBJLIBS	= ../../lib_go_base.a
OBJS =	go_base.o

all: $(OBJLIBS)

$(OBJLIBS):
	$(ECHO) lib_go_base

clean:
	$(ECHO) cleaning up in go_base

force_look:
	true
