/*
  Copyrights reserved
  Written by Paul Hwang
  File name: base_mgr_protocol.h
*/

#pragma once

#define BASE_MGR_PROTOCOL_COMMAND_CREATE_BASE "C"
#define BASE_MGR_PROTOCOL_COMMAND_DELETE_BASE "D"

#define BASE_MGR_PROTOCOL_BASE_ID_SIZE 4
#define BASE_MGR_PROTOCOL_BASE_INDEX_SIZE 4
#define BASE_MGR_PROTOCOL_BASE_ID_INDEX_SIZE (BASE_MGR_PROTOCOL_BASE_ID_SIZE + BASE_MGR_PROTOCOL_BASE_INDEX_SIZE)
